// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class FeaturedTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void featured() {
    driver.get("https://demo.opencart.com/");
    driver.manage().window().setSize(new Dimension(1050, 708));
    driver.findElement(By.cssSelector(".col:nth-child(1) > form .img-fluid")).click();
    driver.findElement(By.id("button-cart")).click();
    js.executeScript("window.scrollTo(0,200)");
    driver.findElement(By.cssSelector(".btn-light:nth-child(1)")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".btn-group > .btn:nth-child(2)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".btn-group > .btn:nth-child(2)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".fa-exchange-alt")).click();
    driver.findElement(By.cssSelector(".fas:nth-child(1) > .far")).click();
    driver.findElement(By.cssSelector(".fas:nth-child(2) > .far")).click();
    driver.findElement(By.linkText("0 reviews")).click();
    driver.findElement(By.cssSelector(".rating > p")).click();
    driver.findElement(By.cssSelector("main")).click();
    driver.findElement(By.cssSelector("div:nth-child(2) > a:nth-child(1) > .img-thumbnail")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("div:nth-child(2) > a:nth-child(1) > .img-thumbnail"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".image > div")).click();
    driver.findElement(By.cssSelector("a:nth-child(2) > .img-thumbnail")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("a:nth-child(2) > .img-thumbnail"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector("a:nth-child(3) > .img-thumbnail")).click();
    driver.findElement(By.cssSelector(".mfp-close")).click();
    driver.findElement(By.cssSelector("a:nth-child(4) > .img-thumbnail")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("a:nth-child(4) > .img-thumbnail"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".mfp-close")).click();
    driver.findElement(By.id("specification-tab")).click();
    driver.findElement(By.id("review-tab")).click();
    driver.findElement(By.id("button-review")).click();
    driver.findElement(By.id("input-rating")).click();
    driver.findElement(By.cssSelector(".form-check-input:nth-child(2)")).click();
    driver.findElement(By.id("input-rating")).click();
    driver.findElement(By.cssSelector(".form-check-input:nth-child(3)")).click();
    driver.findElement(By.id("button-review")).click();
  }
}
