// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class FooteroptionsTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void footeroptions() {
    driver.get("https://demo.opencart.com/");
    driver.manage().window().setSize(new Dimension(1050, 708));
    driver.findElement(By.cssSelector(".col-sm-3:nth-child(1) > h5")).click();
    driver.findElement(By.linkText("Terms & Conditions")).click();
    driver.findElement(By.linkText("Contact Us")).click();
    driver.findElement(By.id("input-enquiry")).click();
    driver.findElement(By.cssSelector(".btn-primary")).click();
    driver.findElement(By.linkText("Returns")).click();
    driver.findElement(By.cssSelector(".form-check-inline:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".form-check-inline:nth-child(2)")).click();
    driver.findElement(By.id("input-opened-no")).click();
    driver.findElement(By.cssSelector(".btn-primary:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".col-sm-3:nth-child(2) li:nth-child(3)")).click();
    driver.findElement(By.linkText("Site Map")).click();
    driver.findElement(By.linkText("Brands")).click();
    driver.findElement(By.linkText("Gift Certificates")).click();
    driver.findElement(By.id("input-theme-6")).click();
    driver.findElement(By.cssSelector(".btn-primary")).click();
  }
}
