// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class HeaderoptionTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void headeroption() {
    driver.get("https://demo.opencart.com/");
    driver.manage().window().setSize(new Dimension(1050, 708));
    js.executeScript("window.scrollTo(0,744)");
    driver.findElement(By.cssSelector(".list-inline-item > .d-none")).click();
    driver.findElement(By.cssSelector(".fa-phone")).click();
    driver.findElement(By.cssSelector(".show > .d-none")).click();
    driver.findElement(By.cssSelector(".fa-user")).click();
    driver.findElement(By.cssSelector(".fa-user")).click();
    driver.findElement(By.linkText("Register")).click();
    driver.findElement(By.cssSelector(".show > .d-none")).click();
    driver.findElement(By.linkText("Login")).click();
    driver.findElement(By.cssSelector("#wishlist-total > .d-none")).click();
    driver.findElement(By.cssSelector(".list-inline-item:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".fa-heart")).click();
    driver.findElement(By.cssSelector(".list-inline-item:nth-child(4) .d-none")).click();
    driver.findElement(By.cssSelector("a > .fa-shopping-cart")).click();
    driver.findElement(By.linkText("Continue")).click();
    driver.findElement(By.cssSelector(".list-inline-item:nth-child(5) .d-none")).click();
    driver.findElement(By.linkText("Continue")).click();
  }
}
